# Generated by Django 5.0.3 on 2026-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
