# Generated by Django 5.0.3 on 2026-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_like_count_delete_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='needs_processing',
            field=models.BooleanField(default=False, verbose_name='待处理封面/时长'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('private', '私密')], db_index=True, default='public', max_length=10, verbose_name='可见性'),
        ),
    ]
