# Generated by Django 5.0.3 on 2026-03-17 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('video_approved', '视频审核通过'), ('video_rejected', '视频审核驳回'), ('file_approved', '文件审核通过'), ('file_rejected', '文件审核驳回'), ('video_public', '视频转为公开'), ('file_public', '文件转为公开')], max_length=30, unique=True, verbose_name='模板标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题模板')),
                ('content', models.TextField(help_text='可用变量: {title}, {username}', verbose_name='内容模板')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
