# Generated by Django 5.0.3 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('icon', models.CharField(max_length=50, verbose_name='图标类名')),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='uploads/files/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('archive', '压缩包'), ('audio', '音乐'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私密')], default='public', max_length=10, verbose_name='可见性')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('file_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.fileitem', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件评论',
                'verbose_name_plural': '文件评论',
            },
        ),
    ]
