# Generated by Django 5.0.3 on 2026-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_delete_filecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('private', '私密')], db_index=True, default='public', max_length=10, verbose_name='可见性'),
        ),
    ]
